Handle the case when we have multiple valid entries after filtering e…
Jellyfish-Insights/andromeda pull request #105
Opened 2021-07-29 13:04 UTC by josiasal

We are getting some crashes due to multiple instances being selected:

 ```csharp
var storedObj = dlContext.Videos.SingleOrDefault(v => v.VideoId == newObj.VideoId && v.ValidityStart <= now && now < v.ValidityEnd);
```
In the example above, that filtering returns multiple instances, so `SingleOrDefault` raises an exception, and the fetcher crashes.

We change it to `LastOfDefault`.

2021-07-29 13:43 UTC, filipelbc-ba commented
@josiasal This is not right.

Note that we filter by validity, meaning there can only be 1 or 0. `.SingleOrDefault` is performing an implicity a validity check. Switching to `.LastOrDefault` hides the inconsistency.

What you need to do is fix in the database, by invalidating the older row. I.e. the validity end of the older row should be equal to the validity start of the newer row.

The question remains regarding why/how such inconsistency came to be.

2021-07-29 13:44 UTC, filipelbc-ba requested changes
See comment.

2021-07-30 13:01 UTC, josiasal commented
@filipelbc-ba, see the updated code.

2021-07-30 13:24 UTC, filipelbc-ba approved these changes
Looks good

2021-07-30 13:25 UTC, merged